# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.6.0
maven_group = net.weyne1.randomcrafts
archives_name = random_crafts
enabled_platforms = fabric,neoforge

# find pack formats here: https://minecraft.wiki/w/Pack_format
datapack_name=randomcrafts
mc_min_pack_format=[101, 1]
mc_max_pack_format=[101, 1]
datapack_description=RandomCrafts generated recipes

# Minecraft properties
minecraft_version = 26.1

# find versions here: https://parchmentmc.org/docs/getting-started
parchment_version = 2025.12.20

# Dependencies
architectury_api_version = 20.0.4
fabric_loader_version = 0.19.2
fabric_api_version = 0.145.1+26.1
neoforge_version = 26.1.2.8-beta
